#!/usr/bin/env bash
# Corrects configuration of nginx server to resolve bugs
ln -s /etc/nginx/sites-available/my_site /etc/nginx/sites-enabled/
rm /etc/nginx/sites-enabled/default
service nginx restart
