#!/usr/bin/env bash
# This Bash script installs Nginx on an Ubuntu machine, configuring it to:
# - Listen on port 80.
# - Return a page containing "Holberton School" when queried at the root with a curl GET request.

apt-get update
apt-get install -y nginx

mkdir -p /etc/nginx/html
echo "Holberton School" > /etc/nginx/html/index.html

cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;
}
EOF

service nginx restart
