#!/usr/bin/env bash
# This Bash script configures a new Ubuntu machine to install and set up Nginx.
# Nginx should listen on port 80 and return a page containing "Holberton School" at the root.

# Update package list and install Nginx
apt-get update
apt-get install -y nginx

# Create the directory for HTML files and write the content to index.html
echo "Holberton School" > /var/www/html/index.html

# Restart Nginx
service nginx restart

# Check Nginx status
systemctl status nginx

# Test Nginx response
curl -s localhost
